# Generated by Django 4.2.5 on 2023-09-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado_solicitud',
            field=models.CharField(choices=[('en_espera', 'En Espera'), ('aprobado', 'Aprobado'), ('otros', 'Otros')], default='en_espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
