# Generated by Django 4.2.5 on 2023-09-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_solicitudcredito_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_credito',
            field=models.CharField(choices=[('credito_personal', 'Crédito Personal'), ('credito_hipotecario', 'Crédito Hipotecario'), ('credito_automotriz', 'Crédito Automotriz')], default='credito_personal', max_length=20),
        ),
    ]
