# Generated by Django 4.2.5 on 2023-09-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_solicitudcredito_tipo_credito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcredito',
            options={'ordering': ['cliente'], 'verbose_name': 'Solicitud de Credito', 'verbose_name_plural': 'Solicitudes de Credito'},
        ),
    ]
