# Generated by Django 4.2.5 on 2023-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_solicitudcredito_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_solicitado',
            field=models.IntegerField(max_length=10),
        ),
    ]
