# Generated by Django 4.2.5 on 2023-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_alter_solicitudcredito_monto_solicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_solicitado',
            field=models.IntegerField(),
        ),
    ]
