# Generated by Django 4.2.5 on 2023-11-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_alter_solicitudcredito_monto_solicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado_solicitud',
            field=models.CharField(choices=[('espera', 'En Espera'), ('aprobado', 'Aprobado'), ('rechazada', 'Rechazada'), ('otros', 'Otros')], default='en_espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='tipo_credito',
            field=models.CharField(choices=[('consumo', 'Crédito de Consumo'), ('hipotecario', 'Crédito Hipotecario'), ('automotriz', 'Crédito Automotriz')], default='credito_personal', max_length=20),
        ),
    ]
