# Generated by Django 4.2.5 on 2023-11-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0011_alter_solicitudcredito_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcredito',
            options={'ordering': ['-fecha_registro', 'cliente'], 'verbose_name': 'Solicitud de Credito', 'verbose_name_plural': 'Solicitudes de Credito'},
        ),
    ]
