# Generated by Django 4.2.5 on 2023-12-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0013_alter_solicitudcredito_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_solicitado',
            field=models.CharField(),
        ),
    ]
