# Generated by Django 4.2.5 on 2023-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0014_alter_solicitudcredito_monto_solicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='fecha_aprobacion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
