# Generated by Django 4.2.5 on 2023-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_banco_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
