# Generated by Django 4.2.5 on 2023-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_banco_direccion_banco_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='fecha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
