# Generated by Django 4.2.5 on 2023-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellidos',
            new_name='apellido_materno',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(default='Gutierrez', max_length=100),
            preserve_default=False,
        ),
    ]
