# Generated by Django 4.2.5 on 2023-09-06 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_apellidos_cliente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
