# Generated by Django 4.2.5 on 2023-09-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='visibilidad',
            field=models.BooleanField(default=True, verbose_name='Visibilidad'),
        ),
    ]
