# Generated by Django 4.2.5 on 2023-10-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_visibilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido_paterno'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
