# Generated by Django 4.2.5 on 2023-11-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['fecha_registro'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
