# Generated by Django 4.2.5 on 2023-11-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro', 'rut'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
