# Generated by Django 4.2.5 on 2023-09-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecutivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={'ordering': ['id_banco'], 'verbose_name': 'Ejecutivo', 'verbose_name_plural': 'Ejecutivos'},
        ),
    ]
