# Generated by Django 4.2.5 on 2023-11-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_banco_direccion_banco_telefono'),
        ('ejecutivo', '0003_ejecutivo_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecutivo',
            name='id_banco',
            field=models.ForeignKey(limit_choices_to={'visibilidad': True}, on_delete=django.db.models.deletion.CASCADE, to='banco.banco'),
        ),
    ]
