# Generated by Django 4.2.5 on 2023-11-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecutivo', '0004_alter_ejecutivo_id_banco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={'ordering': ['id_banco', 'nombre', 'apellido_paterno', 'apellido_materno'], 'verbose_name': 'Ejecutivo', 'verbose_name_plural': 'Ejecutivos'},
        ),
    ]
