# Generated by Django 4.2.5 on 2023-09-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud', '0001_initial'),
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='solicitud_credito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitudcredito'),
        ),
    ]
