# Generated by Django 4.2.5 on 2023-09-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('otros', 'Otros')], default='activo', max_length=20),
        ),
    ]
