# Generated by Django 4.2.5 on 2023-11-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0008_alter_solicitudcredito_estado_solicitud_and_more'),
        ('credito', '0005_credito_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credito',
            name='solicitud_credito',
            field=models.OneToOneField(limit_choices_to={'visibilidad': True}, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitudcredito'),
        ),
    ]
