# Generated by Django 4.2.5 on 2023-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0007_alter_credito_solicitud_credito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credito',
            options={'ordering': ['-fecha_registro', 'estado'], 'verbose_name': 'Credito', 'verbose_name_plural': 'Creditos'},
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
