# Generated by Django 4.2.5 on 2023-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0008_alter_credito_options_credito_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
