# Generated by Django 4.2.5 on 2023-09-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('tipo_pago', models.CharField(max_length=20)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.credito')),
            ],
        ),
    ]
