# Generated by Django 4.2.5 on 2023-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_pago_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente'), ('atrasado', 'Atrasado'), ('otros', 'Otros')], default='realizado', max_length=20),
        ),
    ]
