# Generated by Django 4.2.5 on 2023-11-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0006_alter_credito_monto_alter_credito_solicitud_credito'),
        ('pago', '0005_alter_pago_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='credito',
            field=models.ForeignKey(limit_choices_to={'visibilidad': True}, on_delete=django.db.models.deletion.CASCADE, to='credito.credito'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_pagado',
            field=models.IntegerField(),
        ),
    ]
