# Generated by Django 4.2.5 on 2023-12-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0007_alter_pago_options_pago_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_pagado',
            field=models.CharField(),
        ),
    ]
