# Generated by Django 4.2.5 on 2023-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0008_alter_pago_monto_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.CharField(),
        ),
    ]
